# Generated by Django 5.0.2 on 2024-02-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BANCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BANNOME', models.CharField(max_length=255)),
                ('BANSIGLA', models.CharField(max_length=255)),
            ],
        ),
    ]
